name = "user/cadano_learning_module_1"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'user/cadano_learning_module_1'"

[repository]
user = "user"
project = "cadano_learning_module_1"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
